import "server-only";
// Convenção: toda createX lista TODAS as colunas/keys do tipo no insert, mesmo com null/[]/{}/""
import bcrypt from "bcryptjs";
import { and, count, eq, inArray } from "drizzle-orm";
import { db } from "@/lib/db/client";
import {
  agendamentos,
  agentes,
  clientes,
  clientesAutomacoes,
  emptyLoja,
  emptyVendedor,
  leads,
  type HorariosVendedor,
  type Vendedor,
} from "@/lib/db/schema";
import { defaultCrmStatusColunas } from "@/lib/crm/slots";

async function loadVendedores(clienteId: number): Promise<Vendedor[]> {
  const c = await db.query.clientes.findFirst({
    where: eq(clientes.id, clienteId),
  });
  return Array.isArray(c?.vendedores) ? (c.vendedores as Vendedor[]) : [];
}

async function saveVendedores(clienteId: number, vendedores: Vendedor[]) {
  await db
    .update(clientes)
    .set({ vendedores: vendedores as never })
    .where(eq(clientes.id, clienteId));
}

function nextVendedorId(vendedores: Vendedor[]): number {
  // ID baseado em timestamp ms — colisão entre cadastros simultâneos
  // exige sub-milissegundo, praticamente impossível em produção. Mantém
  // ordem cronológica e dispensa lock no jsonb. Acrescenta jitter de
  // 0–999 pra cobrir o caso raro de 2 chamadas no mesmo ms.
  let candidate = Date.now() * 1000 + Math.floor(Math.random() * 1000);
  const taken = new Set(vendedores.map((v) => v.id));
  while (taken.has(candidate)) candidate += 1;
  return candidate;
}

// ===== CLIENTE =====
export async function deleteCliente(
  clienteId: number,
  { skipChecks = false }: { skipChecks?: boolean } = {},
): Promise<{
  leadsRemovidos: number;
  agendamentosRemovidos: number;
  agentesRemovidos: number;
  automacoesRemovidas: number;
}> {
  // Bloqueio: não permite remover superadmin (Looper).
  if (!skipChecks) {
    const c = await db
      .select({ isSuperadmin: clientes.isSuperadmin })
      .from(clientes)
      .where(eq(clientes.id, clienteId))
      .limit(1);
    if (c[0]?.isSuperadmin === true) {
      throw new Error(
        "Cliente superadmin (Looper) não pode ser removido pela UI.",
      );
    }
  }

  // Cascade manual — não há FK formal porque vendedor virou jsonb.
  // Remove leads + agendamentos + agentes desse cliente.
  // Ordem importa: agendamentos referenciam leads (lead_id).
  const leadsDoCliente = await db
    .select({ id: leads.id })
    .from(leads)
    .where(eq(leads.clienteId, clienteId));
  const leadIds = leadsDoCliente.map((l) => l.id);

  let agendamentosRemovidos = 0;
  if (leadIds.length > 0) {
    const r = await db
      .delete(agendamentos)
      .where(inArray(agendamentos.leadId, leadIds))
      .returning({ id: agendamentos.id });
    agendamentosRemovidos = r.length;
  }
  const rLeads = await db
    .delete(leads)
    .where(eq(leads.clienteId, clienteId))
    .returning({ id: leads.id });
  const rAgentes = await db
    .delete(agentes)
    .where(eq(agentes.clienteId, clienteId))
    .returning({ id: agentes.id });

  // Conta instâncias de automações antes do delete cascata (FK
  // ON DELETE CASCADE em cliente_automacoes.cliente_id remove
  // automaticamente — só precisamos contar pra reportar no retorno).
  // Catálogo (`automacoes`) permanece intacto.
  const autosDoCliente = await db
    .select({ id: clientesAutomacoes.id })
    .from(clientesAutomacoes)
    .where(eq(clientesAutomacoes.clienteId, clienteId));
  const automacoesRemovidas = autosDoCliente.length;

  await db.delete(clientes).where(eq(clientes.id, clienteId));

  return {
    leadsRemovidos: rLeads.length,
    agendamentosRemovidos,
    agentesRemovidos: rAgentes.length,
    automacoesRemovidas,
  };
}

export async function createCliente(data: {
  nome: string;
  email: string;
  senha: string;
  crmTenant: string;
  telefone?: string | null;
  apiToken?: string | null;
  apiInstanciaNome?: string | null;
  apiBaseUrl?: string | null;
  crmToken?: string | null;
  crmOrigemId?: string | null;
  isSuperadmin?: boolean;
} & Record<string, unknown>): Promise<number> {
  const emailLower = data.email.trim().toLowerCase();
  const tenant = data.crmTenant.trim().toLowerCase();
  if (!emailLower) throw new Error("E-mail é obrigatório.");
  if (!tenant) throw new Error("Subdomínio (crm_tenant) é obrigatório.");
  if (data.senha.length < 6) {
    throw new Error("Senha deve ter ao menos 6 caracteres.");
  }

  // Unicidade de tenant — login e roteamento são por subdomínio.
  const existing = await db
    .select({ id: clientes.id })
    .from(clientes)
    .where(eq(clientes.crmTenant, tenant))
    .limit(1);
  if (existing.length > 0) {
    throw new Error(`Subdomínio "${tenant}" já está em uso.`);
  }

  const senhaHash = await bcrypt.hash(data.senha, 10);

  // is_superadmin tem CHECK constraint no banco (só permitido para
  // tenant=looper). Para outros, sempre false.
  const isSuperadmin =
    tenant === "looper" ? data.isSuperadmin === true : false;

  // `clientes.id` é GENERATED BY DEFAULT AS IDENTITY no banco.
  // Postgres gera o id; usamos RETURNING pra recuperar.
  const inserted = await db
    .insert(clientes)
    .values({
      nome: data.nome.trim() || null,
      email: emailLower,
      senha: senhaHash,
      telefone: data.telefone?.trim() || null,
      crmTenant: tenant,
      apiToken: data.apiToken?.trim() || null,
      apiInstanciaNome: data.apiInstanciaNome?.trim() || null,
      apiBaseUrl: data.apiBaseUrl?.trim() || null,
      crmToken: data.crmToken?.trim() || null,
      crmOrigemId: data.crmOrigemId?.trim() || null,
      // Estrutura completa dos 9 slots (slug + tipo preenchidos, nome e
      // id vazios). Admin completa depois via aba CRM ("Buscar do CRM"
      // ou manualmente).
      crmStatusColunas: defaultCrmStatusColunas(),
      isSuperadmin,
      isActive: true,
      // Lojas e vendedores começam com 1 item placeholder pra ancorar o
      // shape canonical no jsonb. Todos os campos presentes com valores
      // vazios — nada disso é lido pela UI até o admin preencher de
      // verdade. Filtros de listagem ignoram itens "vazios" por
      // checagem de campo-chave (loja sem nome, vendedor sem email).
      lojas: [emptyLoja()],
      vendedores: [emptyVendedor()],
    })
    .returning({ id: clientes.id });
  if (!inserted[0]) throw new Error("Insert de cliente não retornou id.");
  const id = inserted[0].id;

  return id;
}

export async function updateCliente(
  clienteId: number,
  patch: {
    nome?: string | null;
    email?: string | null;
    telefone?: string | null;
    apiToken?: string | null;
    apiInstanciaNome?: string | null;
    apiBaseUrl?: string | null;
    crmTenant?: string | null;
    crmToken?: string | null;
    crmOrigemId?: string | null;
    crmStatusColunas?:
      | Array<{
          nome: string;
          id: string;
          slug: string;
          tipo: "inicial" | "qualificacao" | "desqualificacao";
          notUsed?: boolean;
        }>
      | null;
  },
) {
  // Strip undefined — drizzle inclui undefined no SET, sobrescrevendo com NULL.
  const cleaned: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(patch)) {
    if (v !== undefined) cleaned[k] = v;
  }
  if (Object.keys(cleaned).length === 0) return;
  await db
    .update(clientes)
    .set(cleaned as never)
    .where(eq(clientes.id, clienteId));
}

export async function updateClienteSenha(clienteId: number, novaSenha: string) {
  const hash = await bcrypt.hash(novaSenha, 10);
  await db
    .update(clientes)
    .set({ senha: hash })
    .where(eq(clientes.id, clienteId));
}

export async function setClienteLojas(
  clienteId: number,
  lojas: unknown[],
) {
  await db
    .update(clientes)
    .set({ lojas: lojas as never })
    .where(eq(clientes.id, clienteId));
}

// ===== USUARIO =====
export async function updateUsuario(
  clienteId: number,
  usuarioId: number,
  patch: {
    nome?: string | null;
    email?: string | null;
    telefone?: string | null;
    isActive?: boolean;
    crmId?: string | null;
    role?: "owner" | "vendedor";
  },
) {
  const vendedores = await loadVendedores(clienteId);

  // Unicidade de e-mail dentro do tenant.
  // Compara o novo e-mail (lowercase) contra todos os outros vendedores;
  // permite manter o mesmo e-mail do próprio registro.
  if (patch.email !== undefined && patch.email !== null) {
    const novoEmail = patch.email.trim().toLowerCase();
    if (novoEmail) {
      const conflito = vendedores.some(
        (v) => v.id !== usuarioId && (v.email ?? "").toLowerCase() === novoEmail,
      );
      if (conflito) {
        throw new Error(
          "Esse e-mail já está em uso por outro usuário deste tenant.",
        );
      }
    }
  }

  const next = vendedores.map((v) => {
    if (v.id !== usuarioId) return v;
    return {
      ...v,
      nome: patch.nome === undefined ? v.nome : patch.nome,
      email:
        patch.email === undefined
          ? v.email
          : patch.email
            ? patch.email.trim().toLowerCase()
            : null,
      telefone: patch.telefone === undefined ? v.telefone : patch.telefone,
      is_active: patch.isActive === undefined ? v.is_active : patch.isActive,
      crm_id: patch.crmId === undefined ? v.crm_id : patch.crmId,
      role: patch.role === undefined ? v.role : patch.role,
    };
  });
  await saveVendedores(clienteId, next);
  await syncLeadsVendedorSnapshot(clienteId, usuarioId);
}

// Edit inline por célula da tabela /usuarios.
// Aceita campos texto (nome, email, telefone, crmId) e role (select).
export async function updateUsuarioField(
  clienteId: number,
  usuarioId: number,
  field: "nome" | "email" | "telefone" | "crmId" | "role",
  value: string,
) {
  const v = value.trim();
  const patch: Parameters<typeof updateUsuario>[2] = {};
  if (field === "nome") patch.nome = v || null;
  else if (field === "email") patch.email = v || null;
  else if (field === "telefone") patch.telefone = v || null;
  else if (field === "crmId") patch.crmId = v || null;
  else if (field === "role") {
    if (v !== "owner" && v !== "vendedor") {
      throw new Error("Nível inválido. Use 'owner' ou 'vendedor'.");
    }
    patch.role = v;
  }
  await updateUsuario(clienteId, usuarioId, patch);
}

export async function setUsuarioHorarios(
  clienteId: number,
  usuarioId: number,
  horarios: HorariosVendedor,
) {
  const vendedores = await loadVendedores(clienteId);
  const next = vendedores.map((v) =>
    v.id === usuarioId ? { ...v, horarios } : v,
  );
  await saveVendedores(clienteId, next);
  await syncLeadsVendedorSnapshot(clienteId, usuarioId);
}

export async function removeUsuario(
  clienteId: number,
  usuarioId: number,
  options: { transferToId?: number | null } = {},
) {
  const vendedores = await loadVendedores(clienteId);
  const next = vendedores.filter((v) => v.id !== usuarioId);
  if (next.length === vendedores.length) {
    throw new Error("Usuário não encontrado.");
  }

  // Reatribuição de leads do vendedor removido
  if (options.transferToId !== undefined) {
    if (options.transferToId === null) {
      // Liberar (vendedor_id = null) — vão pra fila de não-atribuídos
      await db
        .update(leads)
        .set({ vendedorId: null, vendedor: null })
        .where(
          and(
            eq(leads.clienteId, clienteId),
            eq(leads.vendedorId, usuarioId),
          ),
        );
    } else {
      // Confere se o destino existe na lista atual de vendedores (após remoção)
      const destino = next.find((v) => v.id === options.transferToId);
      if (!destino) {
        throw new Error("Vendedor de destino não encontrado.");
      }
      const snapshot = vendedorSnapshot(destino);
      await db
        .update(leads)
        .set({ vendedorId: options.transferToId, vendedor: snapshot })
        .where(
          and(
            eq(leads.clienteId, clienteId),
            eq(leads.vendedorId, usuarioId),
          ),
        );
    }
  }

  await saveVendedores(clienteId, next);
}

/** Conta leads ativos vinculados a um vendedor. Usado para decidir se o
 *  modal de delete precisa pedir reatribuição. */
export async function countLeadsByVendedor(
  clienteId: number,
  vendedorId: number,
): Promise<number> {
  const r = await db
    .select({ value: count() })
    .from(leads)
    .where(
      and(eq(leads.clienteId, clienteId), eq(leads.vendedorId, vendedorId)),
    );
  return r[0]?.value ?? 0;
}

/** Snapshot do vendedor para a coluna jsonb leads.vendedor. Remove senha. */
function vendedorSnapshot(v: Vendedor): Vendedor {
  const { senha: _senha, ...rest } = v;
  return { ...rest, senha: null } as Vendedor;
}

/** Atribui ou libera vendedor em um lead específico. Grava ID + snapshot. */
export async function setLeadVendedor(
  clienteId: number,
  leadId: number,
  vendedorId: number | null,
) {
  let snapshot: Vendedor | null = null;
  if (vendedorId !== null) {
    const vendedores = await loadVendedores(clienteId);
    const v = vendedores.find((x) => x.id === vendedorId);
    if (!v) throw new Error("Vendedor não encontrado.");
    snapshot = vendedorSnapshot(v);
  }
  await db
    .update(leads)
    .set({ vendedorId, vendedor: snapshot })
    .where(and(eq(leads.id, leadId), eq(leads.clienteId, clienteId)));
}

/** Sincroniza o snapshot vendedor em todos os leads que têm vendedor_id
 *  apontando pra esse usuário. Usado após editar dados do vendedor. */
export async function syncLeadsVendedorSnapshot(
  clienteId: number,
  vendedorId: number,
) {
  const vendedores = await loadVendedores(clienteId);
  const v = vendedores.find((x) => x.id === vendedorId);
  if (!v) {
    // Vendedor não existe mais — limpa snapshot.
    await db
      .update(leads)
      .set({ vendedor: null })
      .where(
        and(eq(leads.clienteId, clienteId), eq(leads.vendedorId, vendedorId)),
      );
    return;
  }
  await db
    .update(leads)
    .set({ vendedor: vendedorSnapshot(v) })
    .where(
      and(eq(leads.clienteId, clienteId), eq(leads.vendedorId, vendedorId)),
    );
}

export async function updateUsuarioSenha(
  clienteId: number,
  usuarioId: number,
  novaSenha: string,
) {
  const hash = await bcrypt.hash(novaSenha, 10);
  const vendedores = await loadVendedores(clienteId);
  const next = vendedores.map((v) =>
    v.id === usuarioId ? { ...v, senha: hash } : v,
  );
  await saveVendedores(clienteId, next);
}

export async function createUsuario(
  clienteId: number,
  data: {
    nome: string;
    email: string;
    senha: string;
    telefone?: string | null;
    crmId?: string | null;
    role?: "owner" | "vendedor";
    recebeAgendamento?: boolean;
    horarios?: HorariosVendedor;
  },
) {
  const vendedores = await loadVendedores(clienteId);
  const emailLower = data.email.toLowerCase();
  if (
    vendedores.some(
      (v) => (v.email ?? "").toLowerCase() === emailLower,
    )
  ) {
    throw new Error("E-mail já cadastrado neste tenant.");
  }
  const hash = await bcrypt.hash(data.senha, 10);
  const novo: Vendedor = {
    id: nextVendedorId(vendedores),
    uid: crypto.randomUUID(),
    loja_ids: [],
    nome: data.nome,
    email: emailLower,
    senha: hash,
    telefone: data.telefone ?? null,
    crm_id: data.crmId ?? null,
    role: data.role ?? "vendedor",
    is_active: true,
    recebe_agendamento: data.recebeAgendamento ?? true,
    ultimo_agendamento: null,
    horarios: data.horarios ?? {},
    created_at: new Date().toISOString(),
  };
  await saveVendedores(clienteId, [...vendedores, novo]);
}

export async function setUsuarioActive(
  clienteId: number,
  usuarioId: number,
  isActive: boolean,
) {
  const vendedores = await loadVendedores(clienteId);
  const next = vendedores.map((v) =>
    v.id === usuarioId ? { ...v, is_active: isActive } : v,
  );
  await saveVendedores(clienteId, next);
  await syncLeadsVendedorSnapshot(clienteId, usuarioId);
}

export async function setUsuarioRecebeAgendamento(
  clienteId: number,
  usuarioId: number,
  recebeAgendamento: boolean,
) {
  const vendedores = await loadVendedores(clienteId);
  const next = vendedores.map((v) =>
    v.id === usuarioId ? { ...v, recebe_agendamento: recebeAgendamento } : v,
  );
  await saveVendedores(clienteId, next);
  await syncLeadsVendedorSnapshot(clienteId, usuarioId);
}

// ===== AGENTE =====

export async function createAgente(
  clienteId: number,
  data: {
    name: string;
    description?: string | null;
    prompt?: string | null;
    debounceTime?: number;
    maxFollowups?: number;
    humanIntervention?: boolean;
    isActive?: boolean;
    voiceGender?: string | null;
    idN8n?: string | null;
  },
): Promise<number> {
  const trimmed = data.name.trim();
  if (!trimmed) throw new Error("Nome do agente é obrigatório.");

  // Confirma que o cliente existe — agente órfão não faz sentido.
  const cli = await db
    .select({ id: clientes.id })
    .from(clientes)
    .where(eq(clientes.id, clienteId))
    .limit(1);
  if (cli.length === 0) throw new Error("Cliente alvo não encontrado.");

  // `agentes.id` é GENERATED ALWAYS AS IDENTITY no banco — proibido
  // passar id explícito. Postgres gera; usamos RETURNING pra recuperar.
  const inserted = await db
    .insert(agentes)
    .values({
      name: trimmed,
      description: data.description ?? null,
      prompt: data.prompt ?? null,
      debounceTime: data.debounceTime ?? 10,
      maxFollowups: data.maxFollowups ?? 5,
      humanIntervention: data.humanIntervention ?? false,
      isActive: data.isActive ?? true,
      clienteId,
      idN8n: data.idN8n ?? null,
      voiceGender: data.voiceGender ?? null,
    })
    .returning({ id: agentes.id });
  if (!inserted[0]) throw new Error("Insert de agente não retornou id.");
  return inserted[0].id;
}

export async function setAgenteActive(
  clienteId: number,
  agenteId: number,
  isActive: boolean,
) {
  await db
    .update(agentes)
    .set({ isActive })
    .where(and(eq(agentes.id, agenteId), eq(agentes.clienteId, clienteId)));
}


export async function updateAgente(
  clienteId: number,
  agenteId: number,
  patch: {
    name?: string;
    description?: string | null;
    prompt?: string | null;
    debounceTime?: number;
    maxFollowups?: number;
    humanIntervention?: boolean;
    isActive?: boolean;
    voiceGender?: string | null;
    idN8n?: string | null;
  },
) {
  await db
    .update(agentes)
    .set(patch)
    .where(and(eq(agentes.id, agenteId), eq(agentes.clienteId, clienteId)));
}

